# Generated by Django 3.1.1 on 2020-09-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.IntegerField(blank=True, null=True)),
                ('delivery_name', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=200)),
                ('delivery_phone', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
