# Generated by Django 3.1.1 on 2020-09-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_delivery_order_payment'),
        ('Product', '0002_auto_20200917_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='User',
            field=models.ManyToManyField(to='Customer.User'),
        ),
    ]
