# Generated by Django 3.1.1 on 2020-09-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20200917_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
