# Generated by Django 3.1.1 on 2020-09-18 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20200918_0911'),
        ('Customer', '0002_delivery_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.cart'),
        ),
        migrations.AddField(
            model_name='user',
            name='Cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.cart'),
        ),
        migrations.AddField(
            model_name='user',
            name='Product',
            field=models.ManyToManyField(to='Product.Product'),
        ),
    ]
