# Generated by Django 3.1.1 on 2020-09-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20200918_0911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
