# Generated by Django 3.1 on 2020-09-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_phone',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
