# Generated by Django 3.1.1 on 2020-09-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductView', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.ImageField(upload_to='Image/'),
        ),
    ]
